default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Recipe_App_development
  username: postgres
  password: murlimohan108

test:
  <<: *default
  database: Recipe_App_test
  username: postgres
  password: murlimohan108

production:
  <<: *default
  database: Recipe_App_production
  username: blog_app
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
